### PR TITLE
fix: ensure a new lock isn't conflicting with itself

### LINKED ISSUE #824: until_and_while_executing not entering perform method on initial run
If I have a worker configured to be locked `until_and_while_executing` and I schedule a worker while sidekiq is not running and then start sidekiq, the worker seems to start and finish (in the console), but never enters the "perform" method. I noticed that if I turn of the reaper, this issue doesn't happen. I'm starting sidekiq immediately after I scheduled the job (so it's not eliminated because if the TTL)

```ruby
class TestWorker
    include Sidekiq::Worker

    sidekiq_options lock: :until_and_while_executing, on_conflict: :log

    def initialize
        puts "Initialize test worker"
        super
    end

    def perform
        puts "Test worker"
    end
end
```

The logs look like the following:

```
2024-01-02T13:05:41.150Z pid=1 tid=64l INFO: Booted Rails 7.1.2 application in development environment
2024-01-02T13:05:41.150Z pid=1 tid=64l INFO: Running in ruby 3.2.2 (2023-03-30 revision e51014f9c0) [aarch64-linux]
2024-01-02T13:05:41.150Z pid=1 tid=64l INFO: See LICENSE and the LGPL-3.0 for licensing details.
2024-01-02T13:05:41.150Z pid=1 tid=64l INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2024-01-02T13:05:41.151Z pid=1 tid=64l INFO: Sidekiq 7.2.0 connecting to Redis with options {:size=>40, :pool_name=>"default", :url=>"redis://redis:6379/2"}
2024-01-02T13:05:41.169Z pid=1 tid=64l uniquejobs=reaper INFO: Starting Reaper
2024-01-02T13:05:41.170Z pid=1 tid=64l INFO: Starting processing, hit Ctrl-C to stop
2024-01-02T13:05:41.175Z pid=1 tid=11bd class=TestWorker jid=a5e3aac198d488050bb5fb95 INFO: start
2024-01-02T13:05:41.182Z pid=1 tid=10mx uniquejobs=reaper INFO: Nothing to delete; exiting.
2024-01-02T13:05:41.185Z pid=1 tid=10mx uniquejobs=reaper INFO: Deleting batch with 1 digests
2024-01-02T13:05:41.186Z pid=1 tid=10mx INFO: (2024-01-02 14:05:41 +0100) Execution successfully returned 1
Initialize test worker
2024-01-02T13:05:41.228Z pid=1 tid=11bd class=TestWorker jid=a5e3aac198d488050bb5fb95 elapsed=0.053 INFO: done
```

This does not happen with for example `until_executed`

In some rare cases the worker is running through: 

```
2024-01-02T13:20:59.477Z pid=1 tid=64l INFO: Booted Rails 7.1.2 application in development environment
2024-01-02T13:20:59.477Z pid=1 tid=64l INFO: Running in ruby 3.2.2 (2023-03-30 revision e51014f9c0) [aarch64-linux]
2024-01-02T13:20:59.477Z pid=1 tid=64l INFO: See LICENSE and the LGPL-3.0 for licensing details.
2024-01-02T13:20:59.477Z pid=1 tid=64l INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2024-01-02T13:20:59.477Z pid=1 tid=64l INFO: Sidekiq 7.2.0 connecting to Redis with options {:size=>40, :pool_name=>"default", :url=>"redis://redis:6379/2"}
2024-01-02T13:20:59.496Z pid=1 tid=64l uniquejobs=reaper INFO: Starting Reaper
2024-01-02T13:20:59.496Z pid=1 tid=64l INFO: Starting processing, hit Ctrl-C to stop
2024-01-02T13:20:59.502Z pid=1 tid=11s1 class=TestWorker jid=37ca7144dc92870517af7293 INFO: start
2024-01-02T13:20:59.510Z pid=1 tid=10mx uniquejobs=reaper INFO: Nothing to delete; exiting.
2024-01-02T13:20:59.511Z pid=1 tid=10mx uniquejobs=reaper INFO: Nothing to delete; exiting.
Initialize test worker
Test worker
2024-01-02T13:20:59.561Z pid=1 tid=11s1 class=TestWorker jid=37ca7144dc92870517af7293 elapsed=0.059 INFO: done
```

I looks to me like a raise condition.

Sidenote: I went down to Sidekiq 6.5.12 and Sidekiq Unique Jobs 7.1.12 and was able to reproduce this bug.

### PR DESCRIPTION
**Pull request by mhenrixon**
This should also improve performance. I still need to create performance tests or benchmarks to tell for sure. 

My test suite time is down to:

CleanShot 2024-02-07 at 12 29 05@2x

Closes #824

### CODE REVIEW

File: lib/sidekiq_unique_jobs/orphans/reaper.rb [hunk 1]
```diff
@@ -22,11 +22,12 @@ class Reaper
       #
       # @return [Hash<Symbol, SidekiqUniqueJobs::Orphans::Reaper] the current implementation of reapers
       REAPERS = {
-        lua: SidekiqUniqueJobs::Orphans::LuaReaper,
+        lua: SidekiqUniqueJobs::Orphans::RubyReaper,
```
Comment (ezekg) [inline lib/sidekiq_unique_jobs/orphans/reaper.rb:25]: Did you mean to change this? 🙂
